language: ruby

rvm:
  - 2.6.3
env:
  global:
    - RAILS_ENV=test

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle-audit check --update
